chore
Former-commit-id: b556acb2b2c8628af49b4432f9326705375a977a

diff --git a/.local/bin/grimblast b/.local/bin/grimblast
--- a/.local/bin/grimblast
+++ b/.local/bin/grimblast
@@ -138,6 +138,30 @@ check() {
   echo "   $COMMAND: $RESULT"
 }
 
+prettier() {
+  FILE=$1
+  GEOM=$2
+  WINDOWS_GEOM=$3
+
+  if [[ $GEOM == *"$WINDOWS_GEOM"* ]]; then
+    w=$(echo $GEOM | awk -F ' |x' '{print$2}')
+    h=$(echo $GEOM | awk -F ' |x' '{print$3}')
+
+    # rounded corners
+    convert $FILE \
+      \( +clone -alpha extract \
+      -draw "fill black rectangle 0,0 $w,$h fill white roundrectangle 0,0 $w,$h 12,12" \
+      \) -alpha off -compose CopyOpacity -composite $FILE
+  fi
+
+  # shadow
+  convert $FILE \( +clone -background black -shadow 120x10+0+0 \) \
+    +swap -background none -layers merge +repage $FILE
+
+  # white backdrop
+  convert $FILE -bordercolor '#893bff' -border 10 $FILE
+}
+
 takeScreenshot() {
   FILE=$1
   GEOM=$2
@@ -148,6 +172,7 @@ takeScreenshot() {
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+    prettier "$FILE" "$GEOM" "$WINDOWS_GEOM"
   fi
 }
 
@@ -191,7 +216,8 @@ elif [ "$SUBJECT" = "area" ]; then
 
   WORKSPACES="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
   WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
-  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp)
+  WINDOWS_GEOM="$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')"
+  GEOM=$(echo $WINDOWS_GEOM | slurp)
 
   if [ ! $hyprpicker_pid -eq -1 ]; then
     kill $hyprpicker_pid
@@ -213,7 +239,8 @@ else
 fi
 
 if [ "$ACTION" = "copy" ]; then
-  takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
+  FILE=/tmp/scr.png
+  takeScreenshot $FILE "$GEOM" "$OUTPUT" && wl-copy --type image/png <"$FILE" || die "Clipboard error"
   notifyOk "$WHAT copied to buffer"
 elif [ "$ACTION" = "save" ]; then
   if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
@@ -237,7 +264,7 @@ elif [ "$ACTION" = "edit" ]; then
   fi
 else
   if [ "$ACTION" = "copysave" ]; then
-    takeScreenshot - "$GEOM" "$OUTPUT" | tee "$FILE" | wl-copy --type image/png || die "Clipboard error"
+    takeScreenshot $FILE "$GEOM" "$OUTPUT" && wl-copy --type image/png <"$FILE" || die "Clipboard error"
     notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
     echo "$FILE"
   else
