a big change
Former-commit-id: a7e545ddd38be8b5c13015b920ba4cb5ab50abb5

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -5,7 +5,7 @@ set shell bash
 set shellopts '-eu'
 set ifs "\n"
 set previewer "~/.config/lf/lf_kitty_preview"
-set cleaner '~/.config/lf/lf_kitty_clean'
+set cleaner "~/.config/lf/lf_kitty_clean"
 set mouse
 # set drawbox
 # set ratios 1:2:3
@@ -26,19 +26,6 @@ map O $mimeopen --ask $f
 map W &setwallpaper.sh $f
 map V invert-below
 map i $bat --paging always $f
-map gt cd ~/.local/share/Trash
-map gr cd /run/media/pxeemo
-
-# define a custom 'open' command
-# This command is called when current file is not a directory. You may want to
-# use either file extensions and/or mime types here. Below uses an editor for
-# text files and a file opener for the rest.
-cmd open &{{
-    case $(file --mime-type -Lb $f) in
-        text/*) lf -remote "send $id \$$EDITOR \$fx";;
-        *) for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done;;
-    esac
-}}
 
 # mkdir command. See wiki if you want it to select created dir
 map a :push %mkdir<space>
@@ -49,85 +36,16 @@ cmd yank-basename $basename -a -- "$fx" | head -c-1 | wl-copy
 
 # cache clean
 cmd clearcache %set -f; rm -rf ~/.cache/thumbnails; echo "thumbnails reseted"
-
-## autojump
-# cmd aj %lf -remote "send $id cd '$(autojump $1 } sed 's/\\/\\\\/g;s/"/\\"/g')'"
-# map a push :aj<space>
-
-# define a custom 'rename' command without prompt for overwrite
-# cmd rename %[ -e $1 ] && printf "file exists" || mv $f $1
-# map r push :rename<space>
-
-# make sure trash folder exists
-# %mkdir -p ~/.trash
-
-# move current file or selected files to trash folder
-# (also see 'man mv' for backup/overwrite options)
-cmd trash %{{
-    set -f 
-    trashdir="${XDG_CONFIG_DIR:-$HOME/.local/share}/Trash"
-    [ -d "$trashdir" ] || mkdir -p "$trashdir"
-
-    for file in $fx; do
-        name="$(basename "$file")"
-        rm -rf "$trashdir/$name"
-        [ -e "$file" ] || (echo "Deleted permanetly!" && exit 0)
-        mv -f "$file" "$trashdir"
-        echo "Trashed at $trashdir/$name."
-    done
-}}
-
-# define a custom 'delete' command
-# cmd delete ${{
-#     set -f
-#     printf "$fx\n"
-#     printf "delete?[y/n]"
-#     read ans
-#     [ "$ans" = "y" ] && rm -rf $fx
-# }}
-
-# use '<delete>' key for either 'trash' or 'delete' command
 map <delete> delete
 map D trash
-# map <delete> delete
-
-# extract the current file with the right command
-# (xkcd link: https://xkcd.com/1168/)
-cmd extract ${{
-    set -f
-    for f in $fx; do
-        x "$f" || continue
-    done
-}}
 map E extract
-
-# compress current file or selected files with tar and gunzip
-cmd tar ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    tar czf $1.tar.gz $1
-    rm -rf $1
-}}
-
-# compress current file or selected files with zip
-cmd zip ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    zip -r $1.zip $1
-    rm -rf $1
-}}
-
-# edit config
-cmd edit-config ${{
-    $EDITOR ~/.config/lf/lfrc
-    lf -remote "send $id source ~/.config/lf/lfrc"
-}}
+map P &mv "$f" .
 
 map C edit-config
 map J :updir; set dironly true; down; set dironly false; open
 map K :updir; set dironly true; up; set dironly false; open
+
+map R bulkrename
 
 cmd bulkrename ${{
     set -f
@@ -153,7 +71,40 @@ cmd bulkrename ${{
     rm -- "$old" "$new"
     lf -remote "send $id unselect"
 }}
-map R bulkrename
+cmd edit-config ${{
+    $EDITOR ~/.config/lf/lfrc
+    lf -remote "send $id source ~/.config/lf/lfrc"
+}}
+cmd extract ${{
+    set -f
+    for f in $fx; do
+        x "$f" || continue
+    done
+}}
+cmd open &{{
+    case $(file --mime-type -Lb $f) in
+        text/*) lf -remote "send $id \$$EDITOR \$fx";;
+        *) for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done;;
+    esac
+}}
+cmd tar ${{
+    set -e # Exit on error
+    mkdir $1
+    cp -r $fx $1
+    tar czf $1.tar.gz $1
+    rm -rf $1
+}}
+cmd trash &{{
+    trash-put $fx
+}}
+cmd zip ${{
+    set -e # Exit on error
+    name="${1:-$f}"
+    mkdir "$name"
+    cp -r $fx "$name"
+    zip -r "$name.zip" "$name"
+    rm -rf "$name"
+}}
 
 cmd z %{{
 	result="$(zoxide query --exclude $PWD $@ | sed 's/\\/\\\\/g;s/"/\\"/g')"
@@ -166,11 +117,6 @@ cmd zi ${{
 }}
 
 cmd on-cd &{{
-        zoxide add "$PWD"
+    zoxide add "$PWD"
 }}
-
-setlocal ~/.local/share/Trash sortby time
-setlocal ~/.local/share/Trash reverse
-setlocal ~/dls/ sortby time
-setlocal ~/dls/ reverse
 
diff --git a/.local/bin/grimmor b/.local/bin/grimmor
--- a/.local/bin/grimmor
+++ b/.local/bin/grimmor
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
-## Grimblast: a helper for screenshots within hyprland
+## Grimmor: a fork of Grimblast helper for screenshots within hyprland
 ## Requirements:
 ##  - `grim`: screenshot utility for wayland
 ##  - `slurp`: to select an area
-##  - `hyprctl`: to read properties of current window
-##  - `wl-copy`: clipboard utility
+##  - `hyprctl`: to read properties of current window (provided by Hyprland)
+##  - `hyprpicker`: to freeze the screen when selecting area
+##  - `wl-copy`: clipboard utility (provided by wl-clipboard)
 ##  - `jq`: json utility to parse hyprctl output
-##  - `notify-send`: to show notifications
+##  - `notify-send`: to show notifications (provided by libnotify)
+##  Optional for `--blur-frame` flag:
+##    - `bc`: to do calculations
+##    - `magick`: to add effects and blur frame (provided by imagemagick)
 ## Those are needed to be installed, if unsure, run `grimblast check`
 ##
 ## See `man 1 grimblast` or `grimblast usage` for further details.
@@ -17,12 +21,24 @@
 ## hyprctl equivalents.
 ## https://github.com/swaywm/sway/blob/master/contrib/grimshot
 
+# Check whether another instance is running
+
+
+grimblastInstanceCheck="${XDG_RUNTIME_DIR:-$XDG_CACHE_DIR:-$HOME/.cache}/grimblast.lock"
+if [ -e "$grimblastInstanceCheck" ]; then
+	exit 2
+else
+	touch "$grimblastInstanceCheck"
+fi
+trap "rm -f '$grimblastInstanceCheck'" EXIT
+
+
 getTargetDirectory() {
   test -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" &&
     . "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"
 
-  dir="${XDG_SCREENSHOTS_DIR:-${XDG_PICTURES_DIR:-$HOME}}"
-  if [[ ! -d "$dir" ]]; then mkdir -p $dir; fi
+  dir="$XDG_PICTURES_DIR/screenshot"
+  [ -d "$dir" ] || mkdir -p "$dir"
   echo "$dir"
 }
 
@@ -43,43 +59,41 @@ env_editor_confirm() {
 NOTIFY=no
 CURSOR=
 FREEZE=
+WAIT=no
 SCALE=
 BLUR_FRAME=no
+HYPRPICKER_PID=-1
 
 while [ $# -gt 0 ]; do
   key="$1"
 
   case $key in
-  -n | --notify)
-    NOTIFY=yes
-    shift # past argument
-    ;;
-  -c | --cursor)
-    CURSOR=yes
-    shift # past argument
-    ;;
-  -f | --freeze)
-    FREEZE=yes
-    shift # past argument
+  -n | --notify) NOTIFY=yes ;;
+  -c | --cursor) CURSOR=yes ;;
+  -f | --freeze) FREEZE=yes ;;
+  -w | --wait)
+    shift
+    WAIT=$1
+    if echo "$WAIT" | grep "[^0-9]" -q; then
+      echo "Invalid value for wait '$WAIT'" >&2
+      exit 3
+    fi
     ;;
   -s | --scale)
     shift # past argument
     if [ $# -gt 0 ]; then
       SCALE="$1" # assign the next argument to SCALE
-      shift      # past argument
     else
       echo "Error: Missing argument for --scale option."
       exit 1
     fi
     ;;
-  --blur-frame)
-    BLUR_FRAME=yes
-    shift # past argument
-    ;;
+  --blur-frame) BLUR_FRAME=yes ;;
   *)      # unknown option
     break # done with parsing --flags
     ;;
   esac
+  shift # past argument
 done
 
 ACTION=${1:-usage}
@@ -89,7 +103,7 @@ FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date -Ins).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--cursor] [--freeze] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--cursor] [--freeze] [--wait N] [--scale <scale>] [--blur-frame] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
@@ -129,7 +143,20 @@ notifyError() {
   fi
 }
 
+resetFade() {
+  if [[ -n $FADELAYERS ]]; then
+    hyprctl keyword animation "$FADELAYERS" >/dev/null
+  fi
+}
+
+killHyprpicker() {
+  if [ ! $HYPRPICKER_PID -eq -1 ]; then
+    kill $HYPRPICKER_PID
+  fi
+}
+
 die() {
+  killHyprpicker
   MSG=${1:-Bye}
   notifyError "Error: $MSG"
   exit 2
@@ -146,38 +173,30 @@ check() {
 }
 
 blurFrame() {
-  [ $BLUR_FRAME == "no" ] && return
   FILE=$1
   GEOM=$2
-  WINDOWS_GEOM=$3
-  w=$(echo $GEOM | awk -F ' |x' '{print$2}')
-  h=$(echo $GEOM | awk -F ' |x' '{print$3}')
-  unit=$(printf "%.f" $(echo "($w+$h)/2*0.1" | bc)) # frame size
-  blur=$(printf "%.f" $(echo $unit/2 | bc)) # blur radius
-  [ $unit -gt 50 ] || unit=50
-  shadow=$(printf "%.f" $(echo $unit/6 | bc)) # shadow size
-  newgeom=$(echo $w+$unit | bc)x$(echo $h+$unit | bc)
+  notroundcorner=$3
 
-  if [[ $GEOM == *"$WINDOWS_GEOM"* ]]; then
-    # rounded corners
+  w=$(echo "$GEOM" | awk -F ' |x' '{print $2}')
+  h=$(echo "$GEOM" | awk -F ' |x' '{print $3}')
+  unit=$(printf "%.f" $(echo "($w+$h)/2*0.1" | bc)) # frame size
+  blur=$(printf "%.f" $(echo "$unit/2" | bc)) # blur radius
+  [ $unit -gt 50 ] || unit=50
+  shadow=$(printf "%.f" $(echo "$unit/4" | bc)) # shadow size
+  newgeom=$(echo "$w+$unit" | bc)x$(echo "$h+$unit" | bc)
+
+  if [[ -z "$notroundcorner" ]]; then
+    # rounding corners
     magick "$FILE" \
       \( +clone -alpha extract \
-      -draw "fill black rectangle 0,0 $w,$h fill white roundrectangle 0,0 $w,$h 14,14" \
+      -draw "fill black rectangle 0,0 "$w,$h" fill white roundrectangle 0,0 "$w,$h" 15,15" \
       \) -alpha off -compose CopyOpacity -composite "$FILE"
   fi
   magick "$FILE" \( +clone -background black -shadow 80x$shadow+0+0 \) \
       +swap -background none -layers merge +repage \
-      -gravity center -background '#ffffff22' -extent "$newgeom" \
-      \( "$FILE" -resize 10% -gaussian-blur 10x$blur -resize "$newgeom^" -extent "$newgeom" \) \
+      -gravity center -background '#ffffff03' -extent "$newgeom" \
+      \( "$FILE" -resize 10% -gaussian-blur "10x$blur" -resize "$newgeom^" -extent "$newgeom" \) \
       +swap -composite "$FILE"
-  # # shadow
-  # magick "$FILE" \( +clone -background black -shadow 100x$shadow+0+0 \) +swap -background none -layers merge +repage /tmp/shadow.png
-  # # frame background shade
-  # magick /tmp/shadow.png -gravity center -background '#ffffff22' -extent "$newgeom" /tmp/border.png
-  # # frame blur
-  # magick "$FILE" -resize 10% -gaussian-blur 10x$blur -resize "$newgeom^" -extent "$newgeom" /tmp/blurred.png
-  # # merge
-  # magick /tmp/blurred.png /tmp/border.png -composite "$FILE"
 }
 
 takeScreenshot() {
@@ -188,10 +207,19 @@ takeScreenshot() {
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
   elif [ -z "$GEOM" ]; then
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
+    screen_res=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | (.width|tostring)+"x"+(.height|tostring)')
+    [ $BLUR_FRAME == "no" ] || blurFrame "$FILE" "0,0 $screen_res" "1"
   else
     grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+    resetFade
+    [ $BLUR_FRAME == "no" ] || blurFrame "$FILE" "$GEOM"
   fi
-  blurFrame "$FILE" "$GEOM" "$WINDOWS_GEOM"
+}
+
+wait() {
+  if [ "$WAIT" != "no" ]; then
+    sleep "$WAIT"
+  fi
 }
 
 if [ "$ACTION" = "check" ]; then
@@ -203,16 +231,21 @@ if [ "$ACTION" = "check" ]; then
   check wl-copy
   check jq
   check notify-send
+  check bc
+  check magick
   exit
 elif [ "$SUBJECT" = "active" ]; then
+  wait
   FOCUSED=$(hyprctl activewindow -j)
   GEOM=$(echo "$FOCUSED" | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
   APP_ID=$(echo "$FOCUSED" | jq -r '.class')
   WHAT="$APP_ID window"
 elif [ "$SUBJECT" = "screen" ]; then
+  wait
   GEOM=""
   WHAT="Screen"
 elif [ "$SUBJECT" = "output" ]; then
+  wait
   GEOM=""
   OUTPUT=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true)' | jq -r '.name')
   WHAT="$OUTPUT"
@@ -220,36 +253,27 @@ elif [ "$SUBJECT" = "area" ]; then
   if [ "$FREEZE" = "yes" ] && [ "$(command -v "hyprpicker")" ] >/dev/null 2>&1; then
     hyprpicker -r -z &
     sleep 0.2
-    hyprpicker_pid=$!
-  else
-    hyprpicker_pid=-1
+    HYPRPICKER_PID=$!
   fi
 
   # get fade & fadeOut animation and unset it
   # this removes the black border seen around screenshots
-  FADE="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fade") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
-  FADEOUT="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeOut") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
-  hyprctl keyword animation 'fade,0,1,default' >/dev/null
-  hyprctl keyword animation 'fadeOut,0,1,default' >/dev/null
+  FADELAYERS="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeLayers") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
+  hyprctl keyword animation 'fadeLayers,0,1,default' >/dev/null
 
-  WORKSPACES="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
+  WORKSPACES="$(hyprctl monitors -j | jq -r '[(foreach .[] as $monitor (0; if $monitor.specialWorkspace.name == "" then $monitor.activeWorkspace else $monitor.specialWorkspace end)).id]')"
   WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
-  WINDOWS_GEOM="$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')"
-  GEOM=$(echo $WINDOWS_GEOM | slurp)
-
-  if [ ! $hyprpicker_pid -eq -1 ]; then
-    kill $hyprpicker_pid
-  fi
-
-  # reset fade
-  hyprctl keyword animation "$FADE" >/dev/null
-  hyprctl keyword animation "$FADEOUT" >/dev/null
+  # shellcheck disable=2086 # if we don't split, spaces mess up slurp
+  GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp $SLURP_ARGS)
 
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
+    killHyprpicker
+    resetFade
     exit 1
   fi
   WHAT="Area"
+  wait
 elif [ "$SUBJECT" = "window" ]; then
   die "Subject 'window' is now included in 'area'"
 else
@@ -257,9 +281,10 @@ else
 fi
 
 if [ "$ACTION" = "copy" ]; then
-  FILE=/tmp/scr.png
+  FILE=$(mktemp --dry-run --suffix ".png")
   takeScreenshot $FILE "$GEOM" "$OUTPUT" && wl-copy --type image/png <"$FILE" || die "Clipboard error"
   notifyOk "$WHAT copied to buffer" -i "$FILE"
+  rm "$FILE"
 elif [ "$ACTION" = "save" ]; then
   if takeScreenshot "$FILE" "$GEOM" "$OUTPUT"; then
     TITLE="Screenshot of $SUBJECT"
@@ -283,9 +308,11 @@ elif [ "$ACTION" = "edit" ]; then
 else
   if [ "$ACTION" = "copysave" ]; then
     takeScreenshot "$FILE" "$GEOM" "$OUTPUT" && wl-copy --type image/png <"$FILE" || die "Clipboard error"
-    notifyOk "$WHAT copied to buffer and saved to pics" -i "$FILE"
+    notifyOk "$WHAT copied to buffer and saved to $FILE" -i "$FILE"
     echo "$FILE"
   else
     notifyError "Error taking screenshot with grim"
   fi
 fi
+
+killHyprpicker
