chore
Former-commit-id: 2e06f6eff1e9641e4868f062137789a266044f45

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -45,6 +45,11 @@ map C edit-config
 map J :updir; set dironly true; down; set dironly false; open
 map K :updir; set dironly true; up; set dironly false; open
 
+map gd cd ~/dls;
+map gc cd ~/.config;
+map gt cd ~/.local/share/Trash;
+map gr cd /run/media/pxeemo;
+
 map R bulkrename
 
 cmd bulkrename ${{
@@ -75,12 +80,13 @@ cmd edit-config ${{
     $EDITOR ~/.config/lf/lfrc
     lf -remote "send $id source ~/.config/lf/lfrc"
 }}
-cmd extract ${{
-    set -f
-    for f in $fx; do
-        x "$f" || continue
-    done
-}}
+cmd extract %x $f
+# cmd extract ${{
+#     set -f
+#     for f in $fx; do
+#         x "$f" || continue
+#     done
+# }}
 cmd open &{{
     case $(file --mime-type -Lb $f) in
         text/*) lf -remote "send $id \$$EDITOR \$fx";;
@@ -91,19 +97,19 @@ cmd tar ${{
     set -e # Exit on error
     mkdir $1
     cp -r $fx $1
-    tar czf $1.tar.gz $1
+    tar -cvf $1.tar.gz $1
     rm -rf $1
 }}
-cmd trash &{{
-    trash-put $fx
-}}
+cmd trash %trash-put -- $fx
 cmd zip ${{
     set -e # Exit on error
     name="${1:-$f}"
-    mkdir "$name"
-    cp -r $fx "$name"
     zip -r "$name.zip" "$name"
-    rm -rf "$name"
+}}
+cmd zstd ${{
+    set -e # Exit on error
+    name="${1:-$f}"
+    tar --zstd -cvf "$name.tar.zst" $fx
 }}
 
 cmd z %{{
@@ -120,3 +126,30 @@ cmd on-cd &{{
     zoxide add "$PWD"
 }}
 
+setlocal ~/.local/share/Trash sortby time
+setlocal ~/.local/share/Trash reverse
+setlocal ~/dls/ sortby time
+setlocal ~/dls/ reverse
+
+# cmd on-select &{{
+#     lf -remote "send $id set statfmt \"$(eza -ld --color=always "$f" | sed 's/\\/\\\\/g;s/"/\\"/g')\""
+# }}
+#
+# cmd on-cd &{{
+#     # display repository status in your prompt
+#     if [ -d .git ] || [ -f .git ]; then
+#         branch="$(git branch --show-current 2>/dev/null)" || true
+#         remote="$(git config --get "branch.$branch.remote" 2>/dev/null)" || true
+#         url="$(git remote get-url "$remote" 2>/dev/null)" || true
+#         fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%w\033[0m\033[33;1m [GIT BRANCH:> $branch >> $url]\033[0m"
+#     elif [ -d .hg ]; then
+#         hg="$(hg branch 2>/dev/null)" || true
+#         fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%w\033[0m\033[33;1m [HG BRANCH:> $hg]\033[0m"
+#     elif [ -d .svn ]; then
+#         svn="$(svn info 2>/dev/null | awk '/^URL: /{print $2}')" || true
+#         fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%w\033[0m\033[33;1m [SVN URL:> $svn]\033[0m"
+#     else
+#         fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%d\033[0m\033[1m%f\033[0m"
+#     fi
+#     lf -remote "send $id set promptfmt \"$fmt\""
+# }}
